config/routes.rb
Rails.application.routes.draw do
  root to: "logins#new"
  resource :login, only: [:new, :create, :destroy]

  resources :messages, only: [:index, :create]

  # Sidekiq dashboard
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :username
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :previews, dependent: :destroy
  # gives extract_urls method to message
  include Twitter::TwitterText::Extractor
  validates :content, presence: true

  def urls
    extract_urls(content).map do |url|
      scheme_present?(url) ? url : "http://#{url}"
    end
  end

  private

  def scheme_present?(url)
    URI.parse(url).scheme.present?
  end
end

app/models/preview.rb
class Preview < ApplicationRecord
  belongs_to :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  private

  def authenticate
    if (username = cookies.encrypted[:username].presence)
      Current.username = username
    else
      redirect_to new_login_path
    end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :authenticate

  def new
    redirect_to messages_path if cookies.encrypted[:username].present?
  end

  def create
    if params[:username].present?
      cookies.encrypted[:username] = params[:username]
      redirect_to messages_path
    else
      redirect_to new_login_path, alert: "Username can't be blank" unless username
    end
  end

  def destroy
    cookies.encrypted[:username] = nil
    redirect_to new_login_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.includes(:previews).last(20)
  end

  def create
    @message = Message.new(message_params)
    @message.author = Current.username
    if @message.save
      DeliverMessageJob.perform_later(@message.id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :delay)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def flex_position(message, &block)
    if message.author == Current.username
      content_tag(:div, capture(&block), class: "d-flex flex-row-reverse")
    else
      content_tag(:div, capture(&block), class: "d-flex flex-row")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le Wagon/Digital Ocean Rails DOKS demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if flash[:alert] %>
      <p><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<%= form_with url: login_path do |f| %>
  <div class="form-row">
  <div class="col">
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="col">
    <%= f.submit "Set Username", class: "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<%= flex_position(message) do %>
  <div class="message-box bg-light my-2 px-3 pt-3 shadow-sm rounded border"
       id="message-<%= message.id %>"
  >
    <div class="text-break">
      <%= message.content %>
      <p class="text-right">
        <small class="text-muted">
          <%= message.author %>
          <%= l(message.created_at, format: :short) %>
        </small>
      </p>
    </div>
    <div class="previews">
    <%= render message.previews %>
    </div>
  </div>
<% end %>

app/views/messages/index.html.erb
<div id="chat" data-controller="chat" data-chat-username="<%= Current.username %>">
  <div class="container" id="navbar-container">
    <div id="navbar" class="py-3 d-flex align-items-center justify-content-between">
      <div class="d-flex" id="logos">
        <%= link_to "https://www.lewagon.com" do %>
          <%= image_tag "wagon-logo.png", width: 50, class: "p-1" %>
        <% end %>
        <%= link_to "https://www.digitalocean.com" do %>
          <%= image_tag "do-logo.png", width: 50, class: "p-1" %>
        <% end %>
      </div>
      <div id="chat-title">
        <p class="h3">
          Rails on
          <%= link_to "DOKS", "https://www.digitalocean.com/products/kubernetes/"%>
          Demo
        </p>
      </div>
      <div>
        <strong><%= Current.username %></strong> |
         <%= link_to "Log Out", login_path, method: :delete %>
      </div>
    </div>
  </div>

  <div class="container" id="messages-container">
    <div id="messages" data-target="chat.messages">
      <%= render @messages %>
    </div>
  </div>

  <div class="container px-0" id="chat-controls-container">
    <div id="chat-controls" class="p-4">
      <%= form_with model: Message.new,
                    id: "chat_form",
                    html: {
                      autocomplete: "off"
                    },
                    data: {
                      target: "chat.form"
                    } do |f|
      %>
        <div class="form-row">
          <div class="col-xs-12 col-sm-10">
            <%= f.text_field :content,
                             class: "form-control",
                              placeholder: "💬 This chat supports URL previews (e.g., lewagon.com)"
            %>
          </div>
          <div class="col" id="chat-submit">
            <%= f.submit "🚀", class: "btn btn-outline-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/previews/_preview.html.erb
<div id="preview-<%= preview.id %>" class="preview-box media my-2">
  <%= image_tag preview.image_url, width: 64, class: "mr-2" if preview.image_url.present? %>
  <div class="media-body">
    <div>
      <%= link_to preview.title, preview.url, class: "text-decoration-none" %>
    </div>
    <small class="text-secondary text-break">
      <%= preview.description %>
    </small>
  </div>
</div>